#!/usr/bin/env python3
"""window_schedule.py -- the window schedule, measured from the layout, and the §12.6 cross-check.

`HOUSE-00380`. `cna-house.md` §12.6 says "full schedule lives in `layout.windows.json`". There is
no such file and there should not be: a window is a portal (`layout.portals.json`) with a leaf
(`layout.openings.json`), and a third file repeating both would be a third thing to keep in step.
The schedule is *derived*, and this derives it.

    tools/world/window_schedule.py --emit      # write docs/window-schedule.md
    tools/world/window_schedule.py --check     # fail if it is stale, or if §12.6 has drifted
    tools/world/window_schedule.py --selftest

## Two outputs, and the second is the one with teeth

`docs/window-schedule.md` is a document: every window in the house with its façade, room, type,
size and sill, plus the counts per façade per level. It is generated, so it cannot be wrong about
the data.

The **cross-check** is the part that matters. §12.6 carries a counts table that a human reads and
a human maintains, and `HOUSE-00376` has already found it disagreeing with §13 by fifteen windows.
`--check` parses that table out of `cna-house.md` and compares it, cell by cell, with what the
layout actually holds. A window added to the data and not to the elevation schedule, or the other
way round, is a failed gate rather than a discrepancy nobody notices for a year.

Offline tooling: not runtime code, not subject to the XNA-only rule.
"""

from __future__ import annotations

import argparse
import collections
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import layout_io  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "assets-src" / "world"
DOCUMENT = REPO / "docs" / "window-schedule.md"
ARCHITECTURE = REPO / "cna-house.md"

#: The building's faces, by the plane a window in them lies in. A window's plane is the room's own
#: coordinate (§15.7 rule 4's wall case), so these are interior faces and not the outer ones §12.6
#: used to quote -- the front reads -14.30 and not -14.00.
FACADES = [
    ("South (front)", "z", (-14.30,)),
    ("North (rear)", "z", (-27.10, -32.10)),
    ("West", "x", (-12.70,)),
    ("East", "x", (8.70,)),
    ("Sunroom flanks", "x", (-6.70, 2.70)),
    ("Garage wing", "x", (17.10,)),
    ("Garden shed", "x", (-16.60,)),
]
LEVELS = ["B1", "L0", "L1", "L2", "L3"]


def facade_of(portal: dict) -> str:
    axis = (portal.get("plane") or {}).get("axis")
    value = float((portal.get("plane") or {}).get("value", 0.0))
    for name, want_axis, values in FACADES:
        if axis == want_axis and any(abs(value - v) < 1e-6 for v in values):
            return name
    return f"unplaced ({axis} = {value:.2f})"


def schedule(directory: Path) -> list[dict]:
    """Every window in the layout, with the façade it is in and the leaf that fills it."""
    layout = layout_io.load_layout(directory)
    if "portals" not in layout:
        return []
    cells = {row.get("id"): row for row in layout_io.rows(layout, "cells")} \
        if "cells" in layout else {}
    leaves = {row.get("portal"): row for row in layout_io.rows(layout, "openings")} \
        if "openings" in layout else {}

    out = []
    for portal in layout_io.rows(layout, "portals"):
        if portal.get("kind") != "window":
            continue
        room = cells.get(portal.get("cellA"), {})
        leaf = leaves.get(portal.get("id"), {})
        u = (portal.get("rect") or {}).get("u") or [0.0, 0.0]
        v = (portal.get("rect") or {}).get("v") or [0.0, 0.0]
        out.append({
            "id": portal.get("id"),
            "facade": facade_of(portal),
            "level": room.get("level", "?"),
            "cell": portal.get("cellA"),
            "onto": portal.get("cellB"),
            "type": leaf.get("type", "—"),
            "width": round(float(u[1]) - float(u[0]), 2),
            "height": round(float(v[1]) - float(v[0]), 2),
            "sill": round(float(v[0]), 2),
            "opacity": portal.get("opacity", "—"),
        })
    out.sort(key=lambda row: ([name for name, _, _ in FACADES].index(row["facade"])
                              if any(row["facade"] == name for name, _, _ in FACADES) else 99,
                              LEVELS.index(row["level"]) if row["level"] in LEVELS else 99,
                              str(row["id"])))
    return out


def counts(rows: list[dict]) -> dict[tuple[str, str], int]:
    return collections.Counter((row["facade"], row["level"]) for row in rows)


def rendered(rows: list[dict]) -> str:
    grid = counts(rows)
    lines = [
        "# Window schedule",
        "",
        "**Generated by `tools/world/window_schedule.py`. Do not edit.**",
        "",
        "Every window in the house, measured from `assets-src/world/layout.portals.json` and",
        "`layout.openings.json`. `cna-house.md` §12.6 carries the counts table below; the",
        "`window-schedule` gate compares the two and fails when they drift.",
        "",
        "## Counts per façade per level",
        "",
        "| Façade | " + " | ".join(LEVELS) + " | Total |",
        "|---" * (len(LEVELS) + 2) + "|",
    ]
    for name, _, _ in FACADES:
        row = [grid.get((name, level), 0) for level in LEVELS]
        if not sum(row):
            continue
        lines.append(f"| {name} | " + " | ".join(str(n) if n else "—" for n in row)
                     + f" | **{sum(row)}** |")
    totals = [sum(grid.get((name, level), 0) for name, _, _ in FACADES) for level in LEVELS]
    lines.append("| **Total** | " + " | ".join(f"**{n}**" for n in totals)
                 + f" | **{sum(totals)}** |")

    lines += ["", "## Every window", "",
              "| Portal | Façade | Level | Room | Onto | Type | W × H | Sill | Opacity |",
              "|---|---|---|---|---|---|---|---|---|"]
    for row in rows:
        lines.append(f"| `{row['id']}` | {row['facade']} | {row['level']} | `{row['cell']}` | "
                     f"`{row['onto']}` | `{row['type']}` | {row['width']:.2f} × "
                     f"{row['height']:.2f} | {row['sill']:+.2f} | {row['opacity']} |")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------- the §12.6 cross-check ---

TABLE_HEAD = re.compile(r"^\|\s*Façade\s*\|\s*B1\s*\|\s*L0\s*\|\s*L1\s*\|\s*L2\s*\|\s*L3\s*\|")


def normalise(name: str) -> str:
    """A façade name as a key, so §12.6's prose and this tool's list can be compared.

    §12.6 writes "South (front, `z = −14.30`)" and this file writes "South (front)". They are the
    same façade, and matching on the raw string would make the cross-check fail the day somebody
    adds the coordinate the reader needs. Backticked spans go, brackets and commas go, and what is
    left is compared case-insensitively.
    """
    without_code = re.sub(r"`[^`]*`", " ", name)
    stripped = re.sub(r"[(),*]", " ", without_code)
    return " ".join(stripped.split()).lower()


def architecture_counts(text: str) -> dict[tuple[str, str], int] | None:
    """§12.6's counts table, parsed. `None` when the table is not there to parse."""
    lines = text.splitlines()
    start = next((index for index, line in enumerate(lines) if TABLE_HEAD.match(line)), None)
    if start is None:
        return None
    parsed: dict[tuple[str, str], int] = {}
    for line in lines[start + 2:]:
        if not line.startswith("|"):
            break
        columns = [column.strip() for column in line.strip().strip("|").split("|")]
        if len(columns) < len(LEVELS) + 1:
            break
        name = normalise(columns[0])
        if name == "total":
            continue
        for level, column in zip(LEVELS, columns[1:1 + len(LEVELS)]):
            digits = re.sub(r"[^0-9]", "", column)
            parsed[(name, level)] = int(digits) if digits else 0
    return parsed


def compare(rows: list[dict], text: str) -> list[str]:
    """Every disagreement between §12.6's table and the layout, named."""
    stated = architecture_counts(text)
    if stated is None:
        return ["cna-house.md: §12.6's counts table was not found; the cross-check cannot run"]
    measured = counts(rows)
    problems = []
    by_key = collections.Counter()
    for (name, level), count in measured.items():
        by_key[(normalise(name), level)] += count
    names = {normalise(name) for name, _, _ in FACADES}
    for name in sorted(names | {key[0] for key in stated}):
        for level in LEVELS:
            was = stated.get((name, level), 0)
            now = by_key.get((name, level), 0)
            if was != now:
                problems.append(f"cna-house.md §12.6: {name} / {level} says {was}, "
                                f"the layout has {now}")
    unplaced = sorted({row["facade"] for row in rows if row["facade"].startswith("unplaced")})
    problems += [f"layout.portals.json: a window is in no known façade -- {face}"
                 for face in unplaced]
    return problems


# ======================================================================================= selftest


def selftest() -> int:
    import copy
    import json
    import shutil
    import tempfile

    failures: list[str] = []

    def require(condition: bool, message: str) -> None:
        print(f"  {'ok  ' if condition else 'FAIL'}  {message}")
        if not condition:
            failures.append(message)

    print("window_schedule: selftest")
    workspace = Path(tempfile.mkdtemp(prefix="window_schedule_selftest_"))
    try:
        world = workspace / "world"
        world.mkdir()
        (world / "layout.levels.json").write_text(json.dumps({
            "schema": "cna-house/levels/1",
            "levels": [{"id": "L0", "ffl": 0.60, "ceiling": 3.30, "structureDepth": 0.35}],
            "construction": {"wallExterior": 0.30},
        }), encoding="utf-8")
        (world / "layout.cells.json").write_text(json.dumps({
            "schema": "cna-house/cells/1",
            "cells": [{"id": "L0_HALL", "level": "L0", "kind": "corridor",
                       "boxes": [{"x": [-2.0, 2.0], "z": [-27.10, -14.30]}]},
                      {"id": "EXT_YARD", "level": "L0", "kind": "exterior",
                       "boxes": [{"x": [-2.0, 2.0], "z": [-14.00, -4.00]}],
                       "yOverride": [0.0, 20.0]}],
        }), encoding="utf-8")
        portals = {"schema": "cna-house/portals/1", "portals": [
            {"id": "P_HALL__YARD__W1", "cellA": "L0_HALL", "cellB": "EXT_YARD",
             "plane": {"axis": "z", "value": -14.30},
             "rect": {"u": [-0.6, 0.6], "v": [1.50, 3.00]},
             "kind": "window", "opacity": "glass", "aperture": "WIN_HALL_1"},
            {"id": "P_HALL__YARD", "cellA": "L0_HALL", "cellB": "EXT_YARD",
             "plane": {"axis": "z", "value": -14.30},
             "rect": {"u": [-2.0, -1.0], "v": [0.60, 2.65]},
             "kind": "door", "opacity": "opaque_when_closed", "aperture": "DOOR_HALL"},
        ]}
        (world / "layout.portals.json").write_text(json.dumps(portals), encoding="utf-8")
        (world / "layout.openings.json").write_text(json.dumps({
            "schema": "cna-house/openings/1", "openings": [
                {"id": "WIN_HALL_1", "kind": "window", "type": "W_DH_STD",
                 "portal": "P_HALL__YARD__W1",
                 "leaf": {"width": 1.18, "height": 1.48, "thickness": 0.030}},
                {"id": "DOOR_HALL", "kind": "door", "type": "D_INT_PASSAGE",
                 "portal": "P_HALL__YARD",
                 "leaf": {"width": 0.96, "height": 2.00, "thickness": 0.040}},
            ]}), encoding="utf-8")

        rows = schedule(world)
        require(len(rows) == 1 and rows[0]["id"] == "P_HALL__YARD__W1",
                f"a door in the same wall is not a window; only the window is scheduled ({rows})")
        require(rows[0]["facade"] == "South (front)" and rows[0]["type"] == "W_DH_STD",
                f"the window is placed on its façade and carries its leaf's type ({rows[0]})")
        require(rows[0]["width"] == 1.20 and rows[0]["sill"] == 1.50,
                f"and its size is the PORTAL's, which is the hole, not the leaf's 1.18 "
                f"({rows[0]['width']}, {rows[0]['sill']})")

        # 1. The cross-check finds a table that agrees...
        agreeing = ("| Façade | B1 | L0 | L1 | L2 | L3 | Total |\n"
                    "|---|---|---|---|---|---|---|\n"
                    "| South (front, `z = -14.30`) | — | 1 | — | — | — | **1** |\n"
                    "| **Total** | — | 1 | — | — | — | **1** |\n")
        require(compare(rows, agreeing) == [],
                f"§12.6's table agreeing with the layout is silent ({compare(rows, agreeing)})")

        # 2. ...and one that does not, cell by cell, saying which cell.
        drifted = agreeing.replace("| South (front, `z = -14.30`) | — | 1 |",
                                   "| South (front, `z = -14.30`) | — | 3 |")
        problems = compare(rows, drifted)
        require(any("south front / L0 says 3" in problem for problem in problems),
                f"a count that drifted is named, with both numbers ({problems})")

        # 3. A window nobody has a façade for is a window nobody can schedule, and saying nothing
        #    about it would make the counts add up while the elevation was missing one.
        stray = copy.deepcopy(portals)
        stray["portals"][0]["plane"] = {"axis": "z", "value": -20.0}
        (world / "layout.portals.json").write_text(json.dumps(stray), encoding="utf-8")
        problems = compare(schedule(world), agreeing)
        require(any("no known façade" in problem for problem in problems),
                f"a window on no known façade is reported ({problems})")
        (world / "layout.portals.json").write_text(json.dumps(portals), encoding="utf-8")

        # 4. The document is stable AND ordered by façade, not by the order the portals file
        #    happens to list things in. Determinism alone would not say so: a file order is
        #    perfectly deterministic and reshuffles the whole document the day a window moves.
        require(rendered(schedule(world)) == rendered(schedule(world)),
                "the document is deterministic")

        two_faces = copy.deepcopy(portals)
        two_faces["portals"].insert(0, {
            "id": "P_HALL__WEST__W1", "cellA": "L0_HALL", "cellB": "EXT_YARD",
            "plane": {"axis": "x", "value": -12.70},
            "rect": {"u": [-20.0, -19.0], "v": [1.50, 3.00]},
            "kind": "window", "opacity": "glass", "aperture": "WIN_HALL_2"})   # sorts BEFORE the south one by id
        (world / "layout.portals.json").write_text(json.dumps(two_faces), encoding="utf-8")
        ordered = [row["facade"] for row in schedule(world)]
        require(ordered == ["South (front)", "West"],
                f"the schedule is in façade order -- south, north, west, east -- and the west "
                f"window is written first in the file AND sorts first by id ({ordered})")
        (world / "layout.portals.json").write_text(json.dumps(portals), encoding="utf-8")

        # 5. A missing table is a failure and not a pass. A cross-check that quietly succeeds when
        #    it cannot find what it is checking is worse than no cross-check.
        require(compare(rows, "# nothing here\n") != [],
                "and a cna-house.md with no §12.6 table fails rather than passing")
    finally:
        shutil.rmtree(workspace, ignore_errors=True)

    if failures:
        print(f"\nwindow_schedule: {len(failures)} claim(s) FAILED")
        return 1
    print("window_schedule: selftest passed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("directory", nargs="?", type=Path, default=SOURCE)
    parser.add_argument("--emit", action="store_true", help="write docs/window-schedule.md")
    parser.add_argument("--check", action="store_true",
                        help="fail if the document is stale or §12.6 has drifted")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        return selftest()

    if not (args.directory / "layout.portals.json").is_file():
        print(f"window_schedule: no portals in {args.directory} yet -- nothing to schedule.")
        return 0

    rows = schedule(args.directory)
    text = rendered(rows)
    problems = compare(rows, ARCHITECTURE.read_text(encoding="utf-8"))

    if args.check:
        stale = not DOCUMENT.is_file() or DOCUMENT.read_text(encoding="utf-8") != text
        if stale:
            problems.append(f"{DOCUMENT.relative_to(REPO)} is stale; run "
                            f"tools/world/window_schedule.py --emit")
        for problem in problems:
            print(f"window_schedule: {problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"window_schedule: {len(rows)} window(s); §12.6 and "
              f"{DOCUMENT.relative_to(REPO)} both match the layout.")
        return 0

    for problem in problems:
        print(f"window_schedule: {problem}", file=sys.stderr)
    DOCUMENT.parent.mkdir(parents=True, exist_ok=True)
    DOCUMENT.write_text(text, encoding="utf-8")
    print(f"window_schedule: wrote {DOCUMENT.relative_to(REPO)} ({len(rows)} windows)")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
