#!/usr/bin/env python3
"""make_smoke_assets.py -- the four assets the content smoke scene needs, authored here.

`HOUSE-00201`. The smoke scene has to load one of each of the six content types the pipeline
supports and *show* that it did. Two of the six already exist and are reused: a vendored Noto face
(`Fonts/ui-22`, `HOUSE-00200`) and the one compiled effect (`Effects/P1Probe`, `HOUSE-00185`). The
other four are generated by this script, which settles their provenance completely (ADR-0012):
there is no source to trace, no licence to read and no third party's media in the repository.

Each one is shaped by what the scene must be able to PROVE, not by what is easiest to write:

* **`Models/Smoke/marker.glb`** -- a 0.8 m cube on the origin plane, 0.8 rather than the fallback's
  1.0 so that a frame showing the fallback instead of the marker is a different picture rather than
  the same one. Its UVs cover the whole texture on every face, which is what lets the texture be
  checked at all.
* **`Textures/Smoke/quadrants.png`** -- four saturated quadrants inside a white border. Four
  because a single colour cannot show that the texture is the right way up, and saturated because a
  quadrant that survives a YUV round trip and a mip chain is still recognisably itself.
* **`Audio/Smoke/chime.wav`** -- 0.30 s of 440 Hz at -6 dBFS with 5 ms fades. The fades are not
  cosmetic: a sine that starts at full amplitude clicks, and a click is exactly the artefact a
  smoke test should not be teaching people to ignore.
* **`Media/Video/smoke_clip.ogv`** -- 64x64, 2 s, 10 fps over a 440 Hz tone, through the
  `VideoImporter` -> `.cnb` -> `Load<Video>` -> `VideoPlayer::GetTexture` path `HOUSE-00098`'s
  probe already proved. The background changes every half second and a black marker steps three
  pixels right **every frame**, so a decoded texture says both which half-second and which frame it
  is -- a player handing back frame 0 forever passes any test that only asks whether a texture came
  back. The frames are PNGs this script authors rather than an `lavfi` graph, for a measured
  reason: `libtheora` here **drops a frame identical to the one before it**, so a flat-colour clip
  encodes to four frames instead of twenty, silently, and the `drawbox` in this ffmpeg has no
  per-frame `eval` with which to move anything.

**What is and is not reproducible.** The PNG, WAV and GLB are written byte for byte by this file
and are reproducible anywhere. The `.ogv` is not: Theora's bitstream depends on the encoder, so a
different ffmpeg produces different bytes for the same input. It is committed once, its hash is in
the manifest, and `--check` re-runs the encode to say whether *this* machine reproduces it -- which
is a diagnosis, not a gate.

    tools/assets/make_smoke_assets.py                 write the assets
    tools/assets/make_smoke_assets.py --check         report without writing
    tools/assets/make_smoke_assets.py --selftest

Offline tooling: not runtime code, not subject to the XNA-only rule.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import make_fallback_assets as fallback  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
ASSETS = REPO / "assets-src"

#: The cube's edge, in metres. NOT 1.0: the fallback box is 1.0, and a smoke frame that quietly
#: showed the fallback would otherwise be indistinguishable from a passing one.
MARKER_EDGE = 0.8

TEXTURE_SIZE = 64
#: Saturated, and four of them, so the texture's orientation is legible in a screenshot and each
#: quadrant is still itself after a mip reduction. Top-left, top-right, bottom-left, bottom-right.
QUADRANTS = ((220, 40, 40), (40, 200, 60), (50, 90, 230), (235, 200, 40))
BORDER = (255, 255, 255)

CHIME_SECONDS = 0.30
CHIME_HZ = 440.0
CHIME_RATE = 44100
#: -6 dBFS. Loud enough to measure, quiet enough that a smoke test does not hurt.
CHIME_AMPLITUDE = 0.5
#: 5 ms of fade at each end. A sine that begins at full amplitude clicks, and a smoke asset that
#: ships a click teaches people that clicks are normal.
CHIME_FADE_SECONDS = 0.005

VIDEO_SIZE = 64
VIDEO_SECONDS = 2
VIDEO_FPS = 10
VIDEO_FRAMES = VIDEO_SECONDS * VIDEO_FPS
#: The background at each half-second, in order. Read back by the smoke scene to prove the frame
#: advanced rather than that a texture merely came back.
VIDEO_COLOURS = ((220, 40, 40), (40, 200, 60), (50, 90, 230), (240, 240, 240))
#: ...and a marker that moves EVERY frame, not every half second. Two reasons, one of them
#: measured: a viewer needs to see motion, and `libtheora` here **drops a frame that is identical
#: to the one before it** -- a two-second flat-colour clip encoded to four frames rather than
#: twenty, silently. Frames that all differ are the only ones that survive the encoder intact.
VIDEO_MARKER_WIDTH = 4
VIDEO_MARKER_HEIGHT = 8


def write_marker(path: Path) -> int:
    """A cube of `MARKER_EDGE` metres, sitting on the origin plane, fully UV-mapped per face."""
    half = MARKER_EDGE / 2.0
    lo, hi = (-half, 0.0, -half), (half, MARKER_EDGE, half)
    faces = [
        ((0, 0, 1), [(0, 0, 1), (1, 0, 1), (1, 1, 1), (0, 1, 1)]),
        ((0, 0, -1), [(1, 0, 0), (0, 0, 0), (0, 1, 0), (1, 1, 0)]),
        ((1, 0, 0), [(1, 0, 1), (1, 0, 0), (1, 1, 0), (1, 1, 1)]),
        ((-1, 0, 0), [(0, 0, 0), (0, 0, 1), (0, 1, 1), (0, 1, 0)]),
        ((0, 1, 0), [(0, 1, 1), (1, 1, 1), (1, 1, 0), (0, 1, 0)]),
        ((0, -1, 0), [(0, 0, 0), (1, 0, 0), (1, 0, 1), (0, 0, 1)]),
    ]
    positions, normals, uvs, indices = [], [], [], []
    for normal, corners in faces:
        base = len(positions)
        for corner, (cx, cy, cz) in enumerate(corners):
            positions.append((lo[0] + cx * (hi[0] - lo[0]),
                              lo[1] + cy * (hi[1] - lo[1]),
                              lo[2] + cz * (hi[2] - lo[2])))
            normals.append(tuple(float(v) for v in normal))
            # The WHOLE texture on every face. A face showing a quarter of it would make the
            # quadrant check depend on which face the camera happened to see.
            uvs.append((float(corner in (1, 2)), float(corner in (2, 3))))
        indices += [base, base + 1, base + 2, base, base + 2, base + 3]

    blob = bytearray()
    views: list[dict] = []
    accessors: list[dict] = []

    def add(data, fmt, component, kind, target):
        offset = len(blob)
        raw = b"".join(struct.pack("<" + fmt, *v) if isinstance(v, tuple)
                       else struct.pack("<" + fmt, v) for v in data)
        blob.extend(raw)
        blob.extend(b"\0" * ((4 - len(raw) % 4) % 4))
        views.append({"buffer": 0, "byteOffset": offset, "byteLength": len(raw), "target": target})
        accessor = {"bufferView": len(views) - 1, "componentType": component,
                    "count": len(data), "type": kind}
        if isinstance(data[0], tuple):
            width = len(data[0])
            accessor["min"] = [min(v[i] for v in data) for i in range(width)]
            accessor["max"] = [max(v[i] for v in data) for i in range(width)]
        else:
            accessor["min"], accessor["max"] = [min(data)], [max(data)]
        accessors.append(accessor)
        return len(accessors) - 1

    a_pos = add(positions, "3f", 5126, "VEC3", 34962)
    a_nrm = add(normals, "3f", 5126, "VEC3", 34962)
    a_uv = add(uvs, "2f", 5126, "VEC2", 34962)
    a_idx = add(indices, "H", 5123, "SCALAR", 34963)

    import json
    document = {
        "asset": {"version": "2.0", "generator": "cna-house tools/assets/make_smoke_assets.py"},
        "scene": 0, "scenes": [{"nodes": [0]}],
        "nodes": [{"name": "SmokeMarker", "mesh": 0}],
        "meshes": [{"name": "SmokeMarker", "primitives": [
            {"attributes": {"POSITION": a_pos, "NORMAL": a_nrm, "TEXCOORD_0": a_uv},
             "indices": a_idx, "mode": 4, "material": 0}]}],
        "materials": [{"name": "SmokeMarkerMaterial", "doubleSided": False,
                       "pbrMetallicRoughness": {"baseColorFactor": [1.0, 1.0, 1.0, 1.0],
                                                "metallicFactor": 0.0, "roughnessFactor": 0.9}}],
        "accessors": accessors, "bufferViews": views, "buffers": [{"byteLength": len(blob)}],
    }
    text = json.dumps(document, separators=(",", ":")).encode("utf-8")
    text += b" " * ((4 - len(text) % 4) % 4)
    out = (struct.pack("<III", 0x46546C67, 2, 12 + 8 + len(text) + 8 + len(blob))
           + struct.pack("<II", len(text), 0x4E4F534A) + text
           + struct.pack("<II", len(blob), 0x004E4942) + bytes(blob))
    path.write_bytes(out)
    return len(out)


def write_quadrants(path: Path) -> int:
    half = TEXTURE_SIZE // 2

    def pixel(x: int, y: int):
        if x == 0 or y == 0 or x == TEXTURE_SIZE - 1 or y == TEXTURE_SIZE - 1:
            return BORDER + (255,)
        return QUADRANTS[(1 if x >= half else 0) + (2 if y >= half else 0)] + (255,)

    return fallback.write_png(str(path), TEXTURE_SIZE, TEXTURE_SIZE, pixel)


def write_chime(path: Path) -> int:
    _write_tone(path, CHIME_SECONDS)
    return path.stat().st_size


def video_frame_pixel(frame: int):
    """The authored content of one frame, as a `(x, y) -> RGBA` function.

    The background says which half-second this is; the marker says which FRAME it is, by stepping
    three pixels to the right every time. Between them a reader of a single decoded texture can
    say exactly where in the clip the player had got to, which is what turns "a texture came back"
    into "the frame advanced".
    """
    background = VIDEO_COLOURS[min(frame * len(VIDEO_COLOURS) // VIDEO_FRAMES,
                                   len(VIDEO_COLOURS) - 1)] + (255,)
    marker_x = frame * 3
    top = VIDEO_SIZE - VIDEO_MARKER_HEIGHT

    def pixel(x: int, y: int):
        if y >= top and marker_x <= x < marker_x + VIDEO_MARKER_WIDTH:
            return (0, 0, 0, 255)
        return background

    return pixel


def video_command(frames: Path, tone: Path, target: Path) -> list[str]:
    """The exact encode, in one place, so `--check` re-runs what writing did.

    The frames are PNGs this script authored rather than an `lavfi` graph, because `lavfi`'s
    `color` source and the `drawbox` filter available here cannot produce a clip whose every frame
    differs -- `drawbox` in this ffmpeg has no per-frame `eval`, so its box never moves, and a clip
    whose frames repeat loses them in the encoder.

    `-fflags/-flags +bitexact` and `-map_metadata -1` remove the muxer's and encoder's version
    stamps, which is as far as reproducibility goes: the Theora bitstream itself still depends on
    the encoder build, and the module docstring says so rather than this pretending otherwise.
    """
    return ["ffmpeg", "-y", "-v", "error", "-fflags", "+bitexact",
            "-framerate", str(VIDEO_FPS), "-i", str(frames / "frame%03d.png"),
            "-i", str(tone),
            "-c:v", "libtheora", "-q:v", "7",
            "-c:a", "libvorbis", "-q:a", "3",
            "-pix_fmt", "yuv420p",
            "-flags", "+bitexact", "-map_metadata", "-1",
            str(target)]


def write_clip(path: Path) -> int:
    if shutil.which("ffmpeg") is None:
        raise SystemExit("make_smoke_assets: ffmpeg is required to author the video clip")
    workspace = Path(tempfile.mkdtemp(prefix="smoke_clip_"))
    try:
        frames = workspace / "frames"
        frames.mkdir()
        for index in range(VIDEO_FRAMES):
            fallback.write_png(str(frames / f"frame{index:03d}.png"),
                               VIDEO_SIZE, VIDEO_SIZE, video_frame_pixel(index))
        tone = workspace / "tone.wav"
        _write_tone(tone, VIDEO_SECONDS)
        result = subprocess.run(video_command(frames, tone, path),
                                capture_output=True, text=True, check=False)
        if result.returncode != 0:
            raise SystemExit(f"make_smoke_assets: ffmpeg failed: {result.stderr.strip()}")
    finally:
        shutil.rmtree(workspace, ignore_errors=True)
    return path.stat().st_size


def _write_tone(path: Path, seconds: float) -> None:
    """The clip's audio track: the same tone as the chime, at the same level, for `seconds`."""
    frames = int(CHIME_RATE * seconds)
    fade = max(int(CHIME_RATE * CHIME_FADE_SECONDS), 1)
    samples = bytearray()
    for index in range(frames):
        envelope = min(index / fade, (frames - 1 - index) / fade, 1.0)
        value = CHIME_AMPLITUDE * envelope * math.sin(2.0 * math.pi * CHIME_HZ * index / CHIME_RATE)
        samples += struct.pack("<h", int(round(value * 32767.0)))
    header = (b"RIFF" + struct.pack("<I", 36 + len(samples)) + b"WAVE"
              + b"fmt " + struct.pack("<IHHIIHH", 16, 1, 1, CHIME_RATE, CHIME_RATE * 2, 2, 16)
              + b"data" + struct.pack("<I", len(samples)))
    path.write_bytes(header + bytes(samples))


#: (relative path, writer). Ordered so the printed report reads the way the scene loads them.
TARGETS = (
    ("Models/Smoke/marker.glb", write_marker),
    ("Textures/Smoke/quadrants.png", write_quadrants),
    ("Audio/Smoke/chime.wav", write_chime),
    ("Media/Video/smoke_clip.ogv", write_clip),
)


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_all(root: Path) -> list[tuple[str, int, str]]:
    written = []
    for relative, writer in TARGETS:
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        size = writer(target)
        written.append((relative, size, digest(target)))
    return written


def check(root: Path) -> int:
    """Re-author each asset into a temporary directory and compare it with what is committed."""
    problems = 0
    workspace = Path(tempfile.mkdtemp(prefix="smoke_assets_check_"))
    try:
        for relative, writer in TARGETS:
            committed = root / relative
            if not committed.is_file():
                print(f"  MISSING  {relative}", file=sys.stderr)
                problems += 1
                continue
            target = workspace / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            try:
                writer(target)
            except SystemExit as error:
                print(f"  SKIPPED  {relative}: {error}")
                continue
            same = digest(target) == digest(committed)
            if same:
                print(f"  same     {relative}")
            elif relative.endswith(".ogv"):
                # Expected, and said plainly. Theora's bitstream depends on the encoder build.
                print(f"  differs  {relative} -- this ffmpeg encodes Theora differently; the "
                      f"committed clip is authoritative and its hash is in the manifest")
            else:
                print(f"  DIFFERS  {relative} -- this file is written byte for byte by this "
                      f"script and should not differ", file=sys.stderr)
                problems += 1
    finally:
        shutil.rmtree(workspace, ignore_errors=True)
    return problems


def selftest() -> int:
    failures = 0

    def require(condition: bool, message: str) -> None:
        nonlocal failures
        if condition:
            print(f"  {message}")
        else:
            print(f"  SELFTEST FAILED: {message}", file=sys.stderr)
            failures += 1

    workspace = Path(tempfile.mkdtemp(prefix="smoke_assets_selftest_"))
    try:
        first = write_all(workspace / "a")
        second = write_all(workspace / "b")

        # The three hand-written formats must be byte-identical run to run. The clip is exempt and
        # that exemption is written into the module docstring rather than hidden here.
        deterministic = [(name, a, b) for (name, _, a), (_, _, b) in zip(first, second)
                         if not name.endswith(".ogv")]
        require(all(a == b for _, a, b in deterministic),
                f"the PNG, WAV and GLB are byte-identical on a second run "
                f"({len(deterministic)} files)")

        # The marker must NOT be the same size as the fallback box, or a frame showing the wrong
        # one looks right.
        marker = (workspace / "a" / "Models/Smoke/marker.glb").read_bytes()
        import json as _json
        length = struct.unpack_from("<I", marker, 12)[0]
        document = _json.loads(marker[20:20 + length].decode("utf-8").rstrip())
        bounds = [accessor for accessor in document["accessors"] if accessor["type"] == "VEC3"][0]
        height = bounds["max"][1] - bounds["min"][1]
        require(abs(height - MARKER_EDGE) < 1e-6 and abs(height - 1.0) > 0.1,
                f"the marker is {height:.2f} m tall, distinguishable from the 1.0 m fallback box")
        require(abs(bounds["min"][1]) < 1e-6,
                "the marker sits ON the origin plane, as origin_check.py requires of a prop")

        texture = workspace / "a" / "Textures/Smoke/quadrants.png"
        from PIL import Image
        with Image.open(texture) as image:
            rgba = image.convert("RGB")
            require(rgba.size == (TEXTURE_SIZE, TEXTURE_SIZE),
                    f"the texture is {rgba.width}x{rgba.height}")
            corners = [rgba.getpixel((16, 16)), rgba.getpixel((48, 16)),
                       rgba.getpixel((16, 48)), rgba.getpixel((48, 48))]
            require(corners == list(QUADRANTS),
                    f"the four quadrants are the four authored colours, in reading order "
                    f"({corners})")
            require(len(set(corners)) == 4,
                    "...and all four are different, so the texture's orientation is legible")
            require(rgba.getpixel((0, 0)) == BORDER,
                    "the border is white, so the texture's extent is visible against any clear "
                    "colour")

        chime = workspace / "a" / "Audio/Smoke/chime.wav"
        data = chime.read_bytes()
        require(data[:4] == b"RIFF" and data[8:12] == b"WAVE", "the chime is a RIFF/WAVE file")
        frames = struct.unpack_from("<I", data, 40)[0] // 2
        require(abs(frames / CHIME_RATE - CHIME_SECONDS) < 1e-3,
                f"it is {frames / CHIME_RATE:.3f} s long at {CHIME_RATE} Hz")
        samples = [struct.unpack_from("<h", data, 44 + 2 * i)[0] for i in range(frames)]
        require(abs(samples[0]) < 200 and abs(samples[-1]) < 200,
                f"it fades in and out rather than clicking (first {samples[0]}, "
                f"last {samples[-1]})")
        peak = max(abs(v) for v in samples)
        require(0.45 * 32767 <= peak <= 0.55 * 32767,
                f"its peak is {20 * math.log10(peak / 32767.0):.1f} dBFS, near the authored -6")
        # A silent file would pass every check above except this one, and silence is exactly what a
        # smoke test must not accept for the asset whose job is to be audible.
        energy = sum(v * v for v in samples) / len(samples)
        require(energy > (0.2 * 32767) ** 2, "it is not silent")

        if shutil.which("ffmpeg") is not None:
            clip = workspace / "a" / "Media/Video/smoke_clip.ogv"
            require(clip.stat().st_size > 1024, f"the clip is {clip.stat().st_size} bytes")
            probe = subprocess.run(
                ["ffprobe", "-v", "error", "-show_entries",
                 "stream=codec_name,width,height,nb_read_frames", "-count_frames",
                 "-of", "csv=p=0", str(clip)],
                capture_output=True, text=True, check=False)
            require("theora" in probe.stdout and f"{VIDEO_SIZE},{VIDEO_SIZE}" in probe.stdout,
                    f"it is Theora at {VIDEO_SIZE}x{VIDEO_SIZE}: "
                    f"{probe.stdout.strip().splitlines()[0] if probe.stdout else '(no output)'}")
            require("vorbis" in probe.stdout, "it carries a Vorbis audio track")
            # EVERY authored frame must survive the encoder. `libtheora` here drops a frame that
            # repeats the one before it, so a flat-colour clip loses four fifths of itself
            # silently; the moving marker is what stops that, and this is the claim that proves it.
            decoded = [int(value) for line in probe.stdout.splitlines()
                       for value in line.split(",")[-1:] if value.isdigit()]
            require(VIDEO_FRAMES in decoded,
                    f"all {VIDEO_FRAMES} authored frames survive the encode ({decoded})")
        else:
            print("  ffmpeg is absent, so the clip's claims are not checked here")
    finally:
        shutil.rmtree(workspace, ignore_errors=True)

    if failures:
        return 1
    print("make_smoke_assets: selftest passed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("root", nargs="?", type=Path, default=ASSETS)
    parser.add_argument("--check", action="store_true",
                        help="re-author into a temporary directory and compare, without writing")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        return selftest()
    if args.check:
        return 1 if check(args.root) else 0

    for relative, size, sha in write_all(args.root):
        print(f"{relative:<34} {size:8d} bytes  {sha[:16]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
