#!/usr/bin/env python3
"""calendar_table.py -- 500 known calendar conversions, from an implementation that is not ours.

`HOUSE-01532`. §35.1's clock counts seconds from 2031-01-01T00:00:00 local STANDARD time, and
`cnahouse::environment` converts that to and from a civil date with Howard Hinnant's algorithm.
A test written against the same arithmetic proves only that the arithmetic is self-consistent, so
the table this emits comes from **Python's `datetime` and `zoneinfo`** -- a different algorithm, a
different language, and, for the daylight-saving column, the IANA database's own record of what
America/New_York actually did.

    tools/ci/calendar_table.py --emit
    tools/ci/calendar_table.py --check
    tools/ci/calendar_table.py --selftest

## What the cases are, and why each group is here

* **The epoch and its neighbours**, including negative seconds: floor arithmetic, not truncation.
* **Both daylight-saving transitions in every year 2007-2040**, to the second either side. 2007 is
  where the table starts because that is when the current US rule took effect; §35 states that rule
  and this project is set in 2031, so the years before it are a history of legislation the code
  deliberately does not carry.
* **Leap years and the century rules**: 2032 and 2036 are leap, 2100 is not, 2000 was.
* **Every month boundary of 2031**, first and last second.
* **A pseudo-random spread** over ±80 years from a fixed seed, so the table is not only the
  interesting cases -- most conversion bugs are found by the boring ones.

## The daylight-saving column

`zoneinfo` is asked whether America/New_York was on daylight saving at that local standard instant.
The epoch is standard time, so the question is asked of the FIXED-OFFSET instant `UTC-5 + t` rather
than of a local wall clock: a wall clock reads 01:30 twice on the November Sunday and `zoneinfo`
would have to guess which one is meant. Asking in UTC has one answer.

Offline tooling: not runtime code, not subject to the XNA-only rule.
"""
from __future__ import annotations

import argparse
import random
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

REPO = Path(__file__).resolve().parents[2]
TABLE = REPO / "tests" / "unit" / "reference" / "calendar.golden.txt"

#: §35.1's epoch: 2031-01-01T00:00:00 local STANDARD time, which is UTC-5.
EPOCH = datetime(2031, 1, 1, 0, 0, 0, tzinfo=timezone(timedelta(hours=-5)))

#: §33's zone. UTC-5 with US rules IS America/New_York, and asking the IANA database rather than
#: restating the rule is what makes this table independent of the code it checks.
ZONE = ZoneInfo("America/New_York")

#: The first year the current US rule (March's second Sunday, November's first) was in force.
RULE_FROM = 2007

#: ...and the last one this table bothers with. 2040 is nine years past the house's own year.
RULE_TO = 2040

HEADER = """\
# 500 known calendar conversions for §35.1's clock. `HOUSE-01532`.
#
# GENERATED by `tools/ci/calendar_table.py --emit` from Python's `datetime` and `zoneinfo`, which
# is a different implementation from the one it checks. Do not edit by hand: `--check` regenerates
# it and compares, and a hand-edited line is a weakened test that nothing else would notice.
#
# Column 1 is §35.1's epoch seconds -- local STANDARD seconds since 2031-01-01T00:00:00-05:00.
# Columns 2-7 are the civil reading of it in local standard time; column 8 is the weekday with
# 0 = Sunday; column 9 the day of the year counting from 1; column 10 is 1 while America/New_York
# was on daylight saving at that instant and 0 otherwise.
#
# Column 11 is 1 when that year is inside the era of the rule §35 states -- March's second Sunday
# to November's first, in force in the United States since 2007. Before that the country began in
# April and ended in October, and 1974 and 1975 were their own emergency arrangements again. The
# clock applies §35's rule to every year and therefore DISAGREES with column 10 wherever column 11
# is 0. That is a stated limitation and not a defect: this house is set in 2031 and the project
# does not carry a history of legislation. Those rows are still worth their place -- their
# CONVERSION columns are checked like every other -- and having them here is what stops the
# limitation being invisible.
#
# epoch\tyear\tmonth\tday\thour\tminute\tsecond\tweekday\tdayOfYear\tdst\tera
"""


def civil(epoch_seconds: int) -> tuple:
    """`(y, m, d, h, mi, s, weekday, day_of_year, dst, era)` for @p epoch_seconds, from Python."""
    moment = EPOCH + timedelta(seconds=epoch_seconds)
    # `weekday()` is 0 = Monday; §35 counts 0 = Sunday, which is what its DST rule is written in.
    weekday = (moment.weekday() + 1) % 7
    day_of_year = moment.timetuple().tm_yday
    # Asked in UTC, of the same instant: a local wall clock reads 01:30 twice on the November
    # Sunday and there would be no way to say which is meant.
    dst = 1 if moment.astimezone(ZONE).dst() else 0
    return (moment.year, moment.month, moment.day, moment.hour, moment.minute, moment.second,
            weekday, day_of_year, dst, 1 if moment.year >= RULE_FROM else 0)


def _at(year: int, month: int, day: int, hour: int = 0, minute: int = 0, second: int = 0) -> int:
    """The epoch second of a local STANDARD civil time."""
    moment = datetime(year, month, day, hour, minute, second, tzinfo=EPOCH.tzinfo)
    return int((moment - EPOCH).total_seconds())


def _nth_weekday(year: int, month: int, weekday: int, nth: int) -> int:
    """The day of the month of the @p nth @p weekday (0 = Sunday), counting from 1."""
    first = datetime(year, month, 1)
    offset = (weekday - (first.weekday() + 1) % 7) % 7
    return 1 + offset + (nth - 1) * 7


def cases() -> list[int]:
    """The 500 epoch seconds the table covers, in order, without duplicates."""
    out: list[int] = []

    def add(second: int) -> None:
        out.append(int(second))

    # 1. The epoch and its neighbours, on both sides of zero.
    for second in (-86401, -86400, -3600, -2, -1, 0, 1, 2, 3600, 86399, 86400):
        add(second)

    # 2. Both transitions, every year the current rule has been in force, to the second either
    #    side. March's second Sunday at 02:00 standard, November's first at 01:00 standard.
    for year in range(RULE_FROM, RULE_TO + 1):
        start = _at(year, 3, _nth_weekday(year, 3, 0, 2), 2, 0, 0)
        end = _at(year, 11, _nth_weekday(year, 11, 0, 1), 1, 0, 0)
        for edge in (start, end):
            add(edge - 1)
            add(edge)

    # 3. Leap years and the century rules, at noon on the day in question.
    for year, month, day in ((2032, 2, 29), (2032, 3, 1), (2036, 2, 29), (2100, 2, 28),
                             (2100, 3, 1), (2000, 2, 29), (1900, 2, 28), (2400, 2, 29)):
        add(_at(year, month, day, 12))

    # 4. Every month boundary of the house's own year, first second and last.
    for month in range(1, 13):
        add(_at(2031, month, 1, 0, 0, 0))
        add(_at(2031, month, 1) - 1)

    # 5. ...and the boring ones, which is where conversion bugs actually live. A fixed seed, so
    #    the table is reproducible and `--check` means something.
    rng = random.Random(20310101)
    span = 80 * 365 * 86400
    while len(set(out)) < 500:
        add(rng.randint(-span, span))

    seen: set[int] = set()
    ordered = []
    for second in out:
        if second not in seen:
            seen.add(second)
            ordered.append(second)
    return ordered[:500]


def render() -> str:
    lines = [HEADER]
    for second in cases():
        lines.append("\t".join(str(value) for value in (second,) + civil(second)) + "\n")
    return "".join(lines)


def selftest() -> int:
    failures = 0

    def require(condition: bool, message: str) -> None:
        nonlocal failures
        print(f"  {'ok  ' if condition else 'FAIL'}  {message}")
        failures += 0 if condition else 1

    rows = cases()
    require(len(rows) == 500, f"the table is {len(rows)} cases")
    require(len(set(rows)) == len(rows), "and every one of them is a different instant")
    require(min(rows) < 0 and max(rows) > 0,
            f"on both sides of the epoch ({min(rows)} to {max(rows)} s)")

    # The DST column is not constant, and it is not merely a summer/winter split either: the four
    # rows at the transitions must differ across a single second.
    edges = 0
    for year in range(RULE_FROM, RULE_TO + 1):
        start = _at(year, 3, _nth_weekday(year, 3, 0, 2), 2, 0, 0)
        end = _at(year, 11, _nth_weekday(year, 11, 0, 1), 1, 0, 0)
        if civil(start - 1)[8] == 0 and civil(start)[8] == 1:
            edges += 1
        if civil(end - 1)[8] == 1 and civil(end)[8] == 0:
            edges += 1
    require(edges == 2 * (RULE_TO - RULE_FROM + 1),
            f"and §35's rule turns over at all {edges} transitions the table straddles, one second "
            f"apart, according to the IANA database rather than to us")

    # The era column exists to make the clock's stated limitation visible, so both values have to
    # be in the table -- and every row outside the era has to be a year the rule really did differ.
    inside = [second for second in rows if civil(second)[9] == 1]
    outside = [second for second in rows if civil(second)[9] == 0]
    require(len(inside) > 100 and len(outside) > 0,
            f"{len(inside)} row(s) are inside §35's rule era and {len(outside)} are before it, so "
            f"the limitation is visible in the table rather than hidden by leaving them out")
    require(all(civil(second)[0] < RULE_FROM for second in outside),
            "and every row outside the era really is before 2007")

    # §31.4's screenshot scene, which is the fixture `HOUSE-01531` was built against: Saturday
    # 14 June 2031, 09:20 local, UTC-4 DST -- so 08:20 STANDARD.
    scene = civil(_at(2031, 6, 14, 8, 20))
    require(scene[:6] == (2031, 6, 14, 8, 20, 0) and scene[6] == 6 and scene[8] == 1,
            f"§31.4's scene is a Saturday in daylight saving, independently ({scene})")

    # Floor and not truncation, which is the whole of what happens before the epoch.
    require(civil(-1)[:6] == (2030, 12, 31, 23, 59, 59), f"-1 s is 2030-12-31T23:59:59 ({civil(-1)})")

    # The rendered table round-trips: reading a line back gives the same instant.
    body = [line for line in render().splitlines() if line and not line.startswith("#")]
    require(len(body) == 500, f"the rendered table has {len(body)} data lines")
    back = 0
    for line in body:
        parts = line.split("\t")
        moment = datetime(*(int(p) for p in parts[1:7]), tzinfo=EPOCH.tzinfo)
        back += 1 if int((moment - EPOCH).total_seconds()) == int(parts[0]) else 0
    require(back == 500, f"and every line's civil reading converts back to its own epoch second "
                         f"({back} of 500)")

    print("calendar_table: selftest passed." if not failures
          else f"calendar_table: {failures} claim(s) FAILED")
    return 1 if failures else 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args(argv)
    if args.selftest:
        return selftest()
    wanted = render()
    if args.emit:
        TABLE.parent.mkdir(parents=True, exist_ok=True)
        TABLE.write_text(wanted, encoding="utf-8")
        print(f"calendar_table: wrote {TABLE.relative_to(REPO)} ({len(cases())} cases)")
        return 0
    if args.check:
        if not TABLE.is_file():
            print(f"calendar_table: {TABLE.relative_to(REPO)} is missing; run --emit")
            return 1
        if TABLE.read_text(encoding="utf-8") != wanted:
            print(f"calendar_table: {TABLE.relative_to(REPO)} is not what this tool produces; "
                  f"it is generated, so run --emit rather than editing it")
            return 1
        print(f"calendar_table: {TABLE.relative_to(REPO)} matches ({len(cases())} cases).")
        return 0
    parser.print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
