#!/usr/bin/env python3
"""Published moonrise times for HOUSE-01601, cached from the USNO.

The source is the United States Naval Observatory Astronomical Applications Department's
`rstt/oneday` API. It uses a full ephemeris; the runtime uses §33.1's deliberately short ELP
series. Sixty independently published crossings therefore test accuracy instead of merely testing
one implementation against a translation of itself.

    tools/ci/moontimes_table.py --fetch      # network; fills cache and table
    tools/ci/moontimes_table.py --emit       # offline; rewrites table from cache
    tools/ci/moontimes_table.py --check      # offline; verifies committed table
    tools/ci/moontimes_table.py --selftest   # offline; verifies this extractor

The USNO is a United States Government institution. Its published data are not subject to
copyright in the United States under 17 U.S.C. 105. Runtime code never reads this fixture.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from datetime import date, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TABLE = REPO / "tests" / "unit" / "reference" / "moontimes.usno.txt"
CACHE = REPO / "tests" / "unit" / "reference" / "moontimes.usno.raw.json"

LATITUDE = 40.05
LONGITUDE = -75.30
TZ_HOURS = -5
API = "https://aa.usno.navy.mil/api/rstt/oneday"
REQUEST_INTERVAL_SECONDS = 0.7
WANTED_ROWS = 60

HEADER = """\
# Published moonrise times for §33.1's `MoonModel`. `HOUSE-01601`.
#
# SOURCE: United States Naval Observatory, Astronomical Applications Department,
#         https://aa.usno.navy.mil/api/rstt/oneday (API version {apiversion}).
# RETRIEVED: {retrieved}
# COORDS: latitude {lat} deg N, longitude {lon} deg -- §33's default location.
# TIMEZONE: UTC{tz:+d}, local STANDARD time; `isdst: false` on every response.
# LICENCE: a work of the United States Government, not subject to copyright in the United States
#          (17 U.S.C. 105). Committed so CI needs no network.
#
# GENERATED by `tools/ci/moontimes_table.py`. Do not edit by hand. The dates are every sixth day
# from 2031-01-01; civil dates on which the USNO publishes no moonrise are retained as null in the
# raw cache and skipped. The first {rows} published rises are emitted.
#
# Columns: year, month, day, moonrise (minutes after local standard midnight).
# year\tmonth\tday\trise
"""


def candidate_dates() -> list[date]:
    """Enough evenly-spaced dates to yield exactly 60 published rises."""
    first = date(2031, 1, 1)
    return [first + timedelta(days=6 * index) for index in range(64)]


def fetch_one(day: date) -> dict:
    url = f"{API}?date={day.isoformat()}&coords={LATITUDE},{LONGITUDE}&tz={TZ_HOURS}"
    with urllib.request.urlopen(url, timeout=30) as response:
        if response.status != 200:
            raise RuntimeError(f"{day}: HTTP {response.status}")
        return json.loads(response.read().decode("utf-8"))


def minutes_of(hhmm: str) -> int:
    hours, minutes = hhmm.split(":")
    return int(hours) * 60 + int(minutes)


def extract(day: date, payload: dict) -> int | None:
    """Return a rise in minutes, or None on a legitimate no-rise civil date."""
    data = payload["properties"]["data"]
    if (data["year"], data["month"], data["day"]) != (day.year, day.month, day.day):
        raise RuntimeError(f"{day}: response carries a different date")
    if data["isdst"]:
        raise RuntimeError(f"{day}: daylight time is forbidden in this standard-time fixture")
    if float(data["tz"]) != float(TZ_HOURS):
        raise RuntimeError(f"{day}: response is for the wrong time zone")
    phenomena = {entry["phen"]: entry["time"] for entry in data["moondata"]}
    return minutes_of(phenomena["Rise"]) if "Rise" in phenomena else None


def selected_rows(cache: dict) -> list[tuple[date, int]]:
    rows = []
    for day in candidate_dates():
        key = day.isoformat()
        if key not in cache["days"]:
            raise RuntimeError(f"cache has no {key}; run --fetch")
        rise = cache["days"][key]
        if rise is not None:
            rows.append((day, int(rise)))
        if len(rows) == WANTED_ROWS:
            break
    if len(rows) != WANTED_ROWS:
        raise RuntimeError(f"only {len(rows)} published rises in cache; need {WANTED_ROWS}")
    return rows


def render() -> str:
    cache = json.loads(CACHE.read_text())
    rows = selected_rows(cache)
    header = HEADER.format(apiversion=cache.get("apiversion", "unknown"),
                           retrieved=cache.get("retrieved", "unknown"),
                           lat=LATITUDE, lon=LONGITUDE, tz=TZ_HOURS, rows=len(rows))
    return header + "".join(
        f"{day.year}\t{day.month}\t{day.day}\t{rise}\n" for day, rise in rows)


def do_fetch() -> int:
    cache: dict = {"source": API, "coords": [LATITUDE, LONGITUDE], "tz": TZ_HOURS, "days": {}}
    if CACHE.exists():
        existing = json.loads(CACHE.read_text())
        if existing.get("coords") == cache["coords"] and existing.get("tz") == cache["tz"]:
            cache.update(existing)
    missing = [day for day in candidate_dates() if day.isoformat() not in cache["days"]]
    print(f"moontimes_table: {len(candidate_dates())} candidates, {len(missing)} to fetch")
    for index, day in enumerate(missing, start=1):
        for attempt in range(4):
            try:
                payload = fetch_one(day)
                break
            except (urllib.error.URLError, TimeoutError, OSError) as error:
                if attempt == 3:
                    print(f"moontimes_table: giving up on {day}: {error}", file=sys.stderr)
                    return 1
                time.sleep(2.0 * (attempt + 1))
        rise = extract(day, payload)
        cache["days"][day.isoformat()] = rise
        cache["apiversion"] = payload.get("apiversion", "unknown")
        if index == 1 or index % 10 == 0:
            print(f"  {index}/{len(missing)}  {day}  rise {rise}")
        time.sleep(REQUEST_INTERVAL_SECONDS)
    if missing:
        cache["retrieved"] = time.strftime("%Y-%m-%d", time.gmtime())
    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True) + "\n")
    return do_emit()


def do_emit() -> int:
    TABLE.write_text(render())
    print(f"moontimes_table: wrote {TABLE.relative_to(REPO)} ({WANTED_ROWS} rows)")
    return 0


def do_check() -> int:
    if not CACHE.exists() or not TABLE.exists():
        print("moontimes_table: fixture missing; run --fetch", file=sys.stderr)
        return 1
    if TABLE.read_text() != render():
        print("moontimes_table: table differs from its cached USNO responses", file=sys.stderr)
        return 1
    print(f"moontimes_table: {TABLE.relative_to(REPO)} matches the cached USNO responses.")
    return 0


def do_selftest() -> int:
    failures = 0

    def ok(label: str, condition: bool) -> None:
        nonlocal failures
        print(f"  {'ok   ' if condition else 'FAIL '} {label}")
        failures += 0 if condition else 1

    dates = candidate_dates()
    ok("candidate dates are sorted and unique", dates == sorted(set(dates)))
    ok("candidate dates cover more than ten lunar months", (dates[-1] - dates[0]).days > 300)
    ok("time parsing covers both ends of a civil day",
       minutes_of("00:00") == 0 and minutes_of("23:59") == 1439)
    good_data = {"year": 2031, "month": 1, "day": 1, "isdst": False, "tz": -5.0,
                 "moondata": [{"phen": "Rise", "time": "11:58"}]}
    good = {"properties": {"data": good_data}}
    ok("a well-formed rise is extracted", extract(date(2031, 1, 1), good) == 718)
    no_rise = {"properties": {"data": {**good_data, "moondata": [{"phen": "Set", "time": "01:02"}]}}}
    ok("a legitimate no-rise day becomes null", extract(date(2031, 1, 1), no_rise) is None)

    def refuses(payload: dict) -> bool:
        try:
            extract(date(2031, 1, 1), payload)
        except RuntimeError:
            return True
        return False

    ok("a response for a different date is refused",
       refuses({"properties": {"data": {**good_data, "day": 2}}}))
    ok("a daylight-time response is refused",
       refuses({"properties": {"data": {**good_data, "isdst": True}}}))
    ok("a response for a different zone is refused",
       refuses({"properties": {"data": {**good_data, "tz": -4.0}}}))
    if CACHE.exists():
        cache = json.loads(CACHE.read_text())
        ok("cache covers all candidate dates",
           all(day.isoformat() in cache.get("days", {}) for day in dates))
        try:
            ok("exactly 60 published rises are selected", len(selected_rows(cache)) == WANTED_ROWS)
        except RuntimeError:
            ok("exactly 60 published rises are selected", False)
    print(f"moontimes_table: selftest {'passed' if failures == 0 else str(failures) + ' FAILED'}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--fetch", action="store_true")
    group.add_argument("--emit", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.fetch:
        return do_fetch()
    if args.emit:
        return do_emit()
    if args.check:
        return do_check()
    return do_selftest()


if __name__ == "__main__":
    sys.exit(main())
