#!/usr/bin/env python3
"""Published noon lunar phases for HOUSE-01602, cached from the USNO.

The USNO `rstt/oneday` service explicitly publishes the Moon's phase name and illuminated fraction
at local noon. This tool extracts sixty evenly spaced 2031 observations. The runtime's phase value
is reconstructed from those two published facts: waxing fractions occupy 0..0.5 and waning
fractions 0.5..1. That conversion is the project's phase coordinate definition, not an ephemeris.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from datetime import date, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TABLE = REPO / "tests" / "unit" / "reference" / "moonphases.usno.txt"
CACHE = REPO / "tests" / "unit" / "reference" / "moonphases.usno.raw.json"

LATITUDE = 40.05
LONGITUDE = -75.30
TZ_HOURS = -5
API = "https://aa.usno.navy.mil/api/rstt/oneday"
REQUEST_INTERVAL_SECONDS = 0.7
ROW_COUNT = 60

HEADER = """\
# Published lunar phase at local noon for §33.2. `HOUSE-01602`.
#
# SOURCE: United States Naval Observatory, Astronomical Applications Department,
#         https://aa.usno.navy.mil/api/rstt/oneday (API version {apiversion}).
# RETRIEVED: {retrieved}
# COORDS: latitude {lat} deg N, longitude {lon} deg; UTC{tz:+d} local STANDARD time.
# LICENCE: United States Government work, not subject to US copyright (17 U.S.C. 105).
# GENERATED by `tools/ci/moonphases_table.py`; `--check` compares this with the offline cache.
#
# `publishedPhase` is derived only from the USNO's published `curphase` and `fracillum` fields:
# waxing: illum/2; waning: 1-illum/2; new: 0; full: 0.5. The API documents both at local noon.
# Columns: year, month, day, illuminated fraction, waxing (0/1), publishedPhase.
# year\tmonth\tday\tillum\twaxing\tphase
"""


def selected_dates() -> list[date]:
    first = date(2031, 1, 1)
    return [first + timedelta(days=6 * index) for index in range(ROW_COUNT)]


def fetch_one(day: date) -> dict:
    url = f"{API}?date={day.isoformat()}&coords={LATITUDE},{LONGITUDE}&tz={TZ_HOURS}"
    with urllib.request.urlopen(url, timeout=30) as response:
        if response.status != 200:
            raise RuntimeError(f"{day}: HTTP {response.status}")
        return json.loads(response.read().decode("utf-8"))


def phase_from(name: str, illuminated: float) -> tuple[bool, float]:
    if name in ("Waxing Crescent", "First Quarter", "Waxing Gibbous"):
        return True, illuminated * 0.5
    if name in ("Waning Gibbous", "Last Quarter", "Waning Crescent"):
        return False, 1.0 - illuminated * 0.5
    if name == "New Moon":
        return True, 0.0
    if name == "Full Moon":
        return False, 0.5
    raise RuntimeError(f"unknown USNO phase name {name!r}")


def extract(day: date, payload: dict) -> tuple[float, bool, float, str]:
    data = payload["properties"]["data"]
    if (data["year"], data["month"], data["day"]) != (day.year, day.month, day.day):
        raise RuntimeError(f"{day}: response carries a different date")
    if data["isdst"] or float(data["tz"]) != float(TZ_HOURS):
        raise RuntimeError(f"{day}: response is not fixed UTC{TZ_HOURS:+d} standard time")
    text = data["fracillum"]
    if not isinstance(text, str) or not text.endswith("%"):
        raise RuntimeError(f"{day}: malformed illuminated fraction {text!r}")
    illuminated = int(text[:-1]) / 100.0
    waxing, phase = phase_from(data["curphase"], illuminated)
    return illuminated, waxing, phase, data["curphase"]


def render() -> str:
    cache = json.loads(CACHE.read_text())
    rows = []
    for day in selected_dates():
        key = day.isoformat()
        if key not in cache["days"]:
            raise RuntimeError(f"cache has no {key}; run --fetch")
        illuminated, waxing, phase, _name = cache["days"][key]
        rows.append(f"{day.year}\t{day.month}\t{day.day}\t{illuminated:.2f}\t{int(waxing)}\t{phase:.3f}")
    header = HEADER.format(apiversion=cache.get("apiversion", "unknown"),
                           retrieved=cache.get("retrieved", "unknown"),
                           lat=LATITUDE, lon=LONGITUDE, tz=TZ_HOURS)
    return header + "\n".join(rows) + "\n"


def do_fetch() -> int:
    cache: dict = {"source": API, "coords": [LATITUDE, LONGITUDE], "tz": TZ_HOURS, "days": {}}
    if CACHE.exists():
        existing = json.loads(CACHE.read_text())
        if existing.get("coords") == cache["coords"] and existing.get("tz") == cache["tz"]:
            cache.update(existing)
    missing = [day for day in selected_dates() if day.isoformat() not in cache["days"]]
    print(f"moonphases_table: {ROW_COUNT} dates, {len(missing)} to fetch")
    for index, day in enumerate(missing, start=1):
        for attempt in range(4):
            try:
                payload = fetch_one(day)
                break
            except (urllib.error.URLError, TimeoutError, OSError) as error:
                if attempt == 3:
                    print(f"moonphases_table: giving up on {day}: {error}", file=sys.stderr)
                    return 1
                time.sleep(2.0 * (attempt + 1))
        extracted = extract(day, payload)
        cache["days"][day.isoformat()] = list(extracted)
        cache["apiversion"] = payload.get("apiversion", "unknown")
        if index == 1 or index % 10 == 0:
            print(f"  {index}/{len(missing)}  {day}  {extracted[3]} {extracted[0]:.0%}")
        time.sleep(REQUEST_INTERVAL_SECONDS)
    if missing:
        cache["retrieved"] = time.strftime("%Y-%m-%d", time.gmtime())
    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True) + "\n")
    return do_emit()


def do_emit() -> int:
    TABLE.write_text(render())
    print(f"moonphases_table: wrote {TABLE.relative_to(REPO)} ({ROW_COUNT} rows)")
    return 0


def do_check() -> int:
    if not CACHE.exists() or not TABLE.exists():
        print("moonphases_table: fixture missing; run --fetch", file=sys.stderr)
        return 1
    if TABLE.read_text() != render():
        print("moonphases_table: table differs from cached USNO data", file=sys.stderr)
        return 1
    print(f"moonphases_table: {TABLE.relative_to(REPO)} matches the cached USNO responses.")
    return 0


def do_selftest() -> int:
    failures = 0

    def ok(label: str, condition: bool) -> None:
        nonlocal failures
        print(f"  {'ok   ' if condition else 'FAIL '} {label}")
        failures += 0 if condition else 1

    dates = selected_dates()
    ok("there are exactly 60 sorted unique dates", len(dates) == 60 and dates == sorted(set(dates)))
    ok("the dates span more than eleven lunations", (dates[-1] - dates[0]).days > 330)
    ok("waxing and waning map to opposite halves",
       phase_from("Waxing Gibbous", 0.60) == (True, 0.30) and
       phase_from("Waning Gibbous", 0.60) == (False, 0.70))
    ok("primary endpoints map exactly",
       phase_from("New Moon", 0.0) == (True, 0.0) and
       phase_from("Full Moon", 1.0) == (False, 0.5))
    good_data = {"year": 2031, "month": 1, "day": 1, "isdst": False, "tz": -5.0,
                 "fracillum": "61%", "curphase": "Waxing Gibbous"}
    good = {"properties": {"data": good_data}}
    ok("a documented API response extracts all published facts",
       extract(date(2031, 1, 1), good) == (0.61, True, 0.305, "Waxing Gibbous"))

    def refuses(payload: dict) -> bool:
        try:
            extract(date(2031, 1, 1), payload)
        except RuntimeError:
            return True
        return False

    ok("a response for another date is refused",
       refuses({"properties": {"data": {**good_data, "day": 2}}}))
    ok("daylight time is refused",
       refuses({"properties": {"data": {**good_data, "isdst": True}}}))
    ok("an unknown phase name is refused",
       refuses({"properties": {"data": {**good_data, "curphase": "Blue Moon"}}}))
    if CACHE.exists():
        cache = json.loads(CACHE.read_text())
        ok("cache covers all 60 dates",
           all(day.isoformat() in cache.get("days", {}) for day in dates))
    print(f"moonphases_table: selftest {'passed' if failures == 0 else str(failures) + ' FAILED'}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--fetch", action="store_true")
    group.add_argument("--emit", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--selftest", action="store_true")
    args = parser.parse_args()
    if args.fetch:
        return do_fetch()
    if args.emit:
        return do_emit()
    if args.check:
        return do_check()
    return do_selftest()


if __name__ == "__main__":
    sys.exit(main())
