#!/usr/bin/env python3
"""suntimes_table.py -- published sunrise and sunset times, from an authority that is not us.

`HOUSE-01561`. §32.1's `SunModel` is a simplified NOAA solar-position algorithm, and its `verify`
line asks for *"200 published sunrise/sunset times, +/- 3 minutes"*. **Published means from an
authority**, and the reason that word is in the criterion is the one `HOUSE-01532` spent a whole
task on: a NOAA implementation checked against a second NOAA implementation written by the same
hand proves the arithmetic is self-consistent and says nothing at all about whether it is right.

The times here come from the **United States Naval Observatory, Astronomical Applications
Department**, `https://aa.usno.navy.mil/api/rstt/oneday` -- the institution that publishes the
Astronomical Almanac. Their rise and set times come from a full ephemeris (DE430-class) with the
standard -0.8333 deg refracted-horizon convention, which is a completely different computation from
§32.1's ~40-flop approximation. That is what makes the comparison worth making.

    tools/ci/suntimes_table.py --fetch      # needs network; writes the cache and the table
    tools/ci/suntimes_table.py --emit       # rewrites the table from the cache, no network
    tools/ci/suntimes_table.py --check      # the committed table matches the cache; no network
    tools/ci/suntimes_table.py --selftest   # the tool's own invariants; no network

## Provenance and licence

Works of the United States Government are not subject to copyright in the United States
(17 U.S.C. 105), and USNO publishes these data for public use. The committed table is a derived
extract -- date, sunrise, sunset, transit -- of 203 days at one location, retained so that CI never
needs the network. The raw responses are kept beside it for the same reason `calendar.golden.txt`
is regenerable: a fixture nobody can reproduce is a fixture nobody can trust.

## Which dates, and why each group is here

* **Every third day of 2031**, the year the house is set in: 122 days, which walks the declination
  curve and the equation of time all the way round once. A solar model that gets the solstices
  right and the shoulders wrong fails here and nowhere else.
* **The 1st and the 15th of every month of 2026, 2032 and 2040**: 72 days spread over fourteen
  years, because §32.1's `n` is days since J2000 and an error in the linear terms grows with it.
  2032 is a leap year and 2040 is nine years the far side of the house's own.
* **The solstices and equinoxes of 2031**, which are where day length is stationary and an error
  in declination shows up as a time error most strongly.

## Times are local STANDARD time, UTC-5, with no daylight saving anywhere in the table

`tz=-5` and nothing else: the API's `isdst` comes back false for July as well as January, which is
what makes every row directly comparable to `SimClock::Standard()`. §35.1's epoch is local standard
seconds for exactly the same reason -- daylight saving is a property of a wall clock's face and not
of where the sun is.

Offline tooling: not runtime code, not subject to the XNA-only rule.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from datetime import date, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TABLE = REPO / "tests" / "unit" / "reference" / "suntimes.usno.txt"
CACHE = REPO / "tests" / "unit" / "reference" / "suntimes.usno.raw.json"

#: §33's location, and the one the whole time subsystem is computed for.
LATITUDE = 40.05
LONGITUDE = -75.30

#: Local STANDARD time, all year. See the module docstring.
TZ_HOURS = -5

API = "https://aa.usno.navy.mil/api/rstt/oneday"

#: Polite. 203 requests at this rate is about three minutes and the endpoint is a public service.
REQUEST_INTERVAL_SECONDS = 0.7

HEADER = """\
# Published sunrise and sunset times for §32.1's `SunModel`. `HOUSE-01561`.
#
# SOURCE: United States Naval Observatory, Astronomical Applications Department,
#         https://aa.usno.navy.mil/api/rstt/oneday (API version {apiversion}).
# RETRIEVED: {retrieved}
# COORDS: latitude {lat} deg N, longitude {lon} deg -- §33's default location.
# TIMEZONE: UTC{tz:+d}, local STANDARD time, no daylight saving on any row (the API returns
#           `isdst: false` for every date here, which is what makes the rows comparable to
#           `SimClock::Standard()` directly).
# LICENCE: a work of the United States Government, not subject to copyright in the United States
#          (17 U.S.C. 105). Committed so that CI needs no network.
#
# GENERATED by `tools/ci/suntimes_table.py`. Do not edit by hand: `--check` regenerates the table
# from the cached responses beside it and compares, and a hand-edited line is a weakened test that
# nothing else would notice. `--fetch` refills the cache from the USNO.
#
# The USNO computes these from a full ephemeris with the standard -0.8333 deg refracted-horizon
# convention. §32.1's model is ~40 flops. The two agreeing to within a few minutes is the claim
# `HOUSE-01561` is making; they are not the same computation and are not expected to be identical.
#
# Columns: year, month, day, sunrise (minutes after local standard midnight), sunset (the same),
#          upper transit (the same). {rows} rows, {times} published rise/set times.
#
# year\tmonth\tday\trise\tset\ttransit
"""


def selected_dates() -> list[date]:
    """The dates the table covers. Deterministic, sorted, no duplicates."""
    wanted: set[date] = set()

    # Every third day of 2031 -- once round the declination curve.
    day = date(2031, 1, 1)
    while day.year == 2031:
        wanted.add(day)
        day += timedelta(days=3)

    # The 1st and the 15th of every month of three years fourteen years apart.
    for year in (2026, 2032, 2040):
        for month in range(1, 13):
            wanted.add(date(year, month, 1))
            wanted.add(date(year, month, 15))

    # The solstices and equinoxes of 2031, where day length is stationary.
    for month, dom in ((3, 20), (6, 21), (9, 23), (12, 21)):
        wanted.add(date(2031, month, dom))

    return sorted(wanted)


def fetch_one(day: date) -> dict:
    """One day's response, as the API returned it. Raises on anything unexpected."""
    url = f"{API}?date={day.isoformat()}&coords={LATITUDE},{LONGITUDE}&tz={TZ_HOURS}"
    with urllib.request.urlopen(url, timeout=30) as response:
        if response.status != 200:
            raise RuntimeError(f"{day}: HTTP {response.status}")
        return json.loads(response.read().decode("utf-8"))


def minutes_of(hhmm: str) -> int:
    """"06:04" -> 364. The API's times are local, HH:MM, 24 hour."""
    hours, minutes = hhmm.split(":")
    return int(hours) * 60 + int(minutes)


def extract(day: date, payload: dict) -> tuple[int, int, int]:
    """The three numbers this table keeps, checked against what was asked for."""
    data = payload["properties"]["data"]
    if (data["year"], data["month"], data["day"]) != (day.year, day.month, day.day):
        raise RuntimeError(f"{day}: the response is for {data['year']}-{data['month']}-{data['day']}")
    if data["isdst"]:
        raise RuntimeError(f"{day}: the response is on daylight saving; the table must be standard time")
    if float(data["tz"]) != float(TZ_HOURS):
        raise RuntimeError(f"{day}: the response is for UTC{data['tz']:+}, not UTC{TZ_HOURS:+d}")
    phenomena = {entry["phen"]: entry["time"] for entry in data["sundata"]}
    for required in ("Rise", "Set", "Upper Transit"):
        if required not in phenomena:
            # At 40 deg N the sun rises and sets every day of the year, so a missing one is a
            # malformed response and never a polar night. Refusing is right.
            raise RuntimeError(f"{day}: the response has no '{required}'")
    return (
        minutes_of(phenomena["Rise"]),
        minutes_of(phenomena["Set"]),
        minutes_of(phenomena["Upper Transit"]),
    )


def do_fetch() -> int:
    days = selected_dates()
    cache: dict = {"source": API, "coords": [LATITUDE, LONGITUDE], "tz": TZ_HOURS, "days": {}}
    if CACHE.exists():
        existing = json.loads(CACHE.read_text())
        if existing.get("coords") == cache["coords"] and existing.get("tz") == cache["tz"]:
            cache["days"] = existing.get("days", {})
            cache["retrieved"] = existing.get("retrieved")
            cache["apiversion"] = existing.get("apiversion")

    missing = [day for day in days if day.isoformat() not in cache["days"]]
    print(f"suntimes_table: {len(days)} date(s) wanted, {len(missing)} to fetch")
    for index, day in enumerate(missing):
        for attempt in range(4):
            try:
                payload = fetch_one(day)
                break
            except (urllib.error.URLError, TimeoutError, OSError) as error:
                if attempt == 3:
                    print(f"suntimes_table: giving up on {day}: {error}", file=sys.stderr)
                    return 1
                time.sleep(2.0 * (attempt + 1))
        rise, sets, transit = extract(day, payload)
        cache["days"][day.isoformat()] = [rise, sets, transit]
        cache["apiversion"] = payload.get("apiversion", "unknown")
        if index % 25 == 0:
            print(f"  {index}/{len(missing)}  {day}  rise {rise}  set {sets}")
        time.sleep(REQUEST_INTERVAL_SECONDS)
    if missing:
        cache["retrieved"] = time.strftime("%Y-%m-%d", time.gmtime())
    CACHE.write_text(json.dumps(cache, indent=1, sort_keys=True) + "\n")
    return do_emit()


def render() -> str:
    cache = json.loads(CACHE.read_text())
    days = selected_dates()
    rows = []
    for day in days:
        key = day.isoformat()
        if key not in cache["days"]:
            raise RuntimeError(f"the cache has no {key}; run --fetch")
        rise, sets, transit = cache["days"][key]
        rows.append(f"{day.year}\t{day.month}\t{day.day}\t{rise}\t{sets}\t{transit}")
    header = HEADER.format(
        apiversion=cache.get("apiversion", "unknown"),
        retrieved=cache.get("retrieved", "unknown"),
        lat=LATITUDE,
        lon=LONGITUDE,
        tz=TZ_HOURS,
        rows=len(rows),
        times=2 * len(rows),
    )
    return header + "\n".join(rows) + "\n"


def do_emit() -> int:
    TABLE.write_text(render())
    print(f"suntimes_table: wrote {TABLE.relative_to(REPO)} ({len(selected_dates())} rows)")
    return 0


def do_check() -> int:
    if not TABLE.exists():
        print("suntimes_table: the table is missing; run --fetch", file=sys.stderr)
        return 1
    if TABLE.read_text() != render():
        print("suntimes_table: the committed table does not match the cached responses", file=sys.stderr)
        return 1
    print(f"suntimes_table: {TABLE.relative_to(REPO)} matches the cached USNO responses.")
    return 0


def do_selftest() -> int:
    failures = 0

    def ok(label: str, condition: bool, detail: str = "") -> None:
        nonlocal failures
        print(f"  {'ok   ' if condition else 'FAIL '} {label}{(' (' + detail + ')') if detail else ''}")
        failures += 0 if condition else 1

    days = selected_dates()
    ok("the date list is sorted and has no duplicates", days == sorted(set(days)), f"{len(days)} dates")
    ok("there are enough dates for the criterion's 200 published times",
       2 * len(days) >= 200, f"{2 * len(days)} rise/set times from {len(days)} dates")
    ok("midnight is minute 0 and 06:04 is minute 364",
       minutes_of("00:00") == 0 and minutes_of("06:04") == 364)
    ok("23:59 is minute 1439, so a time of day always fits a day",
       minutes_of("23:59") == 1439)

    # A response for the wrong day, or on daylight saving, must be refused rather than recorded:
    # a fixture that silently accepts the wrong date is worse than no fixture.
    def refuses(label: str, payload: dict) -> None:
        try:
            extract(date(2031, 6, 21), payload)
        except RuntimeError:
            ok(label, True)
            return
        ok(label, False)

    good = {"properties": {"data": {
        "year": 2031, "month": 6, "day": 21, "isdst": False, "tz": -5.0,
        "sundata": [{"phen": "Rise", "time": "04:32"}, {"phen": "Set", "time": "19:34"},
                    {"phen": "Upper Transit", "time": "12:03"}]}}}
    ok("a well-formed response extracts its three numbers",
       extract(date(2031, 6, 21), good) == (272, 1174, 723))
    refuses("a response for a different date is refused",
            {"properties": {"data": {**good["properties"]["data"], "day": 22}}})
    refuses("a response on daylight saving is refused",
            {"properties": {"data": {**good["properties"]["data"], "isdst": True}}})
    refuses("a response in a different time zone is refused",
            {"properties": {"data": {**good["properties"]["data"], "tz": -4.0}}})
    refuses("a response with no sunset is refused",
            {"properties": {"data": {**good["properties"]["data"],
                                     "sundata": [{"phen": "Rise", "time": "04:32"}]}}})

    if CACHE.exists():
        cache = json.loads(CACHE.read_text())
        have = set(cache.get("days", {}))
        ok("the cache covers every date the table wants",
           all(day.isoformat() in have for day in days), f"{len(have)} cached")

    print(f"suntimes_table: selftest {'passed' if failures == 0 else str(failures) + ' FAILED'}")
    return 1 if failures else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--fetch", action="store_true", help="fetch from the USNO (needs network)")
    group.add_argument("--emit", action="store_true", help="rewrite the table from the cache")
    group.add_argument("--check", action="store_true", help="the table matches the cache")
    group.add_argument("--selftest", action="store_true", help="the tool's own invariants")
    args = parser.parse_args()
    if args.fetch:
        return do_fetch()
    if args.emit:
        return do_emit()
    if args.check:
        return do_check()
    return do_selftest()


if __name__ == "__main__":
    sys.exit(main())
