// SPDX-License-Identifier: MIT
//
// `HOUSE-01532`. §35.1's calendar conversion, both directions, against **500 conversions this
// project did not compute**.
//
// `HOUSE-01531` built the clock and tested it against its own arithmetic: the epoch, the DST rule,
// a handful of anchors and §31.4's screenshot scene. That is worth having and it is not enough --
// a conversion tested against itself proves consistency and nothing about correctness. So the
// table `tests/unit/reference/calendar.golden.txt` is generated by `tools/ci/calendar_table.py`
// from **Python's `datetime` and `zoneinfo`**: a different algorithm, a different language, and,
// for the daylight-saving column, the IANA database's own record of what America/New_York did.
//
// It covers the epoch and its negative neighbours, both transitions of every year from 2007 to
// 2040 to the second either side, the leap-year century rules, every month boundary of 2031, and
// a seeded spread of ordinary instants -- which is where conversion bugs actually live.
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "cnahouse/environment/SimClock.hpp"

namespace
{
    using cnahouse::environment::CivilFromEpochSeconds;
    using cnahouse::environment::CivilTime;
    using cnahouse::environment::DaylightSavingAt;
    using cnahouse::environment::EpochSecondsFor;
    using cnahouse::environment::SimClock;

    constexpr const char* kTable = "tests/unit/reference/calendar.golden.txt";

    struct Row
    {
        std::int64_t epoch = 0;
        CivilTime civil;
        bool daylightSaving = false;
        /// @brief Whether this row's year is inside the era of the rule §35 states.
        ///
        /// The current US rule -- March's second Sunday to November's first -- took effect in
        /// 2007. Before that the country began in April and ended in October, and 1974 and 1975
        /// were emergency arrangements again. The clock applies §35's rule to every year and so
        /// disagrees with the IANA database outside this era, on purpose: the house is set in 2031
        /// and the project does not carry a history of legislation. Those rows' CONVERSION columns
        /// are checked like all the others.
        bool ruleEra = false;
    };

    /// The table, or an empty vector when it is not where the working directory says it is.
    std::vector<Row> ReadTable()
    {
        std::vector<Row> rows;
        std::ifstream file(kTable);
        if (!file)
        {
            return rows;
        }
        std::string line;
        while (std::getline(file, line))
        {
            if (line.empty() || line.front() == '#')
            {
                continue;
            }
            std::istringstream fields(line);
            Row row;
            int dst = 0;
            int era = 0;
            fields >> row.epoch >> row.civil.year >> row.civil.month >> row.civil.day >> row.civil.hour >>
                row.civil.minute >> row.civil.second >> row.civil.weekday >> row.civil.dayOfYear >> dst >>
                era;
            if (!fields)
            {
                continue;
            }
            row.daylightSaving = dst != 0;
            row.ruleEra = era != 0;
            rows.push_back(row);
        }
        return rows;
    }

    std::string Describe(const Row& row)
    {
        char text[96];
        std::snprintf(text,
                      sizeof(text),
                      "%lld s = %04d-%02d-%02dT%02d:%02d:%02d",
                      static_cast<long long>(row.epoch),
                      row.civil.year,
                      row.civil.month,
                      row.civil.day,
                      row.civil.hour,
                      row.civil.minute,
                      row.civil.second);
        return text;
    }

} // namespace

TEST(ClockTests, TheTableIsThereAndIsFiveHundredCases)
{
    // A missing table would make every claim below vacuously true, which is the one way this file
    // could pass while proving nothing.
    ASSERT_TRUE(std::filesystem::exists(kTable))
        << kTable << " is missing; tests run from the repository root and this file is committed";
    const std::vector<Row> rows = ReadTable();
    EXPECT_EQ(rows.size(), 500U) << "the table is not the 500 cases `calendar_table.py` emits";
    // ...and it is not 500 copies of one instant, nor 500 of the same side of the epoch.
    ASSERT_FALSE(rows.empty());
    std::int64_t lowest = rows.front().epoch;
    std::int64_t highest = rows.front().epoch;
    int summertime = 0;
    for (const Row& row : rows)
    {
        lowest = row.epoch < lowest ? row.epoch : lowest;
        highest = row.epoch > highest ? row.epoch : highest;
        summertime += row.daylightSaving ? 1 : 0;
    }
    EXPECT_LT(lowest, 0) << "no case before the epoch, so the floor arithmetic is untested";
    EXPECT_GT(highest, 0);
    EXPECT_GT(summertime, 0) << "no case in daylight saving";
    EXPECT_LT(summertime, static_cast<int>(rows.size())) << "every case in daylight saving";
}

TEST(ClockTests, EveryEpochSecondReadsAsTheDateSomebodyElseSaysItIs)
{
    const std::vector<Row> rows = ReadTable();
    ASSERT_FALSE(rows.empty()) << kTable;
    int checked = 0;
    for (const Row& row : rows)
    {
        const CivilTime read = CivilFromEpochSeconds(static_cast<double>(row.epoch));
        EXPECT_EQ(read.year, row.civil.year) << Describe(row);
        EXPECT_EQ(read.month, row.civil.month) << Describe(row);
        EXPECT_EQ(read.day, row.civil.day) << Describe(row);
        EXPECT_EQ(read.hour, row.civil.hour) << Describe(row);
        EXPECT_EQ(read.minute, row.civil.minute) << Describe(row);
        EXPECT_EQ(read.second, row.civil.second) << Describe(row);
        EXPECT_EQ(read.weekday, row.civil.weekday) << Describe(row) << " -- weekday";
        EXPECT_EQ(read.dayOfYear, row.civil.dayOfYear) << Describe(row) << " -- day of year";
        ++checked;
    }
    std::printf("  %d conversion(s) checked against Python's `datetime`\n", checked);
    EXPECT_EQ(checked, 500);
}

TEST(ClockTests, EveryDateConvertsBackToTheEpochSecondItCameFrom)
{
    // The other direction, and not merely a round trip through our own reading: the input is the
    // table's civil date and the expected output is the table's epoch second, so both ends of the
    // comparison come from Python.
    const std::vector<Row> rows = ReadTable();
    ASSERT_FALSE(rows.empty()) << kTable;
    for (const Row& row : rows)
    {
        EXPECT_DOUBLE_EQ(EpochSecondsFor(row.civil), static_cast<double>(row.epoch)) << Describe(row);
        // `weekday` and `dayOfYear` are outputs of the conversion, so a caller that fills in only
        // the five fields it knows gets the same answer.
        CivilTime partial = row.civil;
        partial.weekday = -1;
        partial.dayOfYear = -1;
        EXPECT_DOUBLE_EQ(EpochSecondsFor(partial), static_cast<double>(row.epoch)) << Describe(row);
    }
}

TEST(ClockTests, TheDaylightSavingVerdictIsTheOneAmericaNewYorkRecorded)
{
    // The strongest column in the table: §35's rule is stated in `cna-house.md` in one sentence,
    // and this compares it against the IANA database's record of what the zone actually did --
    // including the 68 transitions the table straddles to the second.
    const std::vector<Row> rows = ReadTable();
    ASSERT_FALSE(rows.empty()) << kTable;
    int agreed = 0;
    int older = 0;
    int olderDisagreed = 0;
    for (const Row& row : rows)
    {
        const bool ours = DaylightSavingAt(static_cast<double>(row.epoch));
        // The clock reads the free function rather than keeping a second copy of the rule, and
        // that holds whatever era the row is from. §35.2b's compression is off, because this table
        // is a table of CALENDAR instants and the compression makes the date run 24 times faster
        // than the clock face -- `CompressedYearTests` is where the default is checked.
        SimClock clock;
        clock.calendarDaysPerSimDay = 1.0;
        clock.epochSeconds = static_cast<double>(row.epoch);
        EXPECT_EQ(clock.IsDaylightSaving(), ours) << Describe(row);
        clock.dstRulesUS = false;
        EXPECT_FALSE(clock.IsDaylightSaving()) << Describe(row) << " -- with the rule off";

        if (!row.ruleEra)
        {
            // Before 2007 the United States began in April and ended in October. §35's rule is
            // applied to every year, so these rows are EXPECTED to disagree some of the time --
            // they are here for their conversion columns, and counting them is what keeps the
            // limitation visible instead of quietly excluded.
            ++older;
            olderDisagreed += ours != row.daylightSaving ? 1 : 0;
            continue;
        }
        EXPECT_EQ(ours, row.daylightSaving) << Describe(row) << " -- daylight saving";
        agreed += ours == row.daylightSaving ? 1 : 0;
    }
    std::printf("  %d daylight-saving verdict(s) agree with the IANA database; %d row(s) predate "
                "§35's rule era and %d of those disagree, as the rule says they will\n",
                agreed,
                older,
                olderDisagreed);
    EXPECT_GT(agreed, 100) << "too few rows inside §35's rule era for this to mean anything";
    EXPECT_GT(older, 0) << "no row predates the rule era, so the limitation is untested";
    EXPECT_GT(olderDisagreed, 0)
        << "every pre-2007 row agrees with §35's rule, which would mean the era column is not "
           "distinguishing anything and this test is exempting rows for no reason";
}

TEST(ClockTests, TheWallClockIsTheStandardClockPlusTheHourTheRuleIsIn)
{
    // What the two columns are FOR. `epochSeconds` is standard time so the line is monotone; the
    // wall clock is derived, and this is the derivation, checked against the table's own verdict
    // rather than against the clock's.
    const std::vector<Row> rows = ReadTable();
    ASSERT_FALSE(rows.empty()) << kTable;
    for (const Row& row : rows)
    {
        SimClock clock;
        clock.calendarDaysPerSimDay = 1.0;
        clock.epochSeconds = static_cast<double>(row.epoch);
        const CivilTime standard = clock.Standard();
        const CivilTime wall = clock.Wall();
        const bool summer = DaylightSavingAt(static_cast<double>(row.epoch));
        const double difference = EpochSecondsFor(wall) - EpochSecondsFor(standard);
        EXPECT_DOUBLE_EQ(difference, summer ? 3600.0 : 0.0) << Describe(row);
        EXPECT_EQ(clock.EffectiveUtcOffsetMinutes(),
                  cnahouse::environment::kDefaultUtcOffsetMinutes + (summer ? 60 : 0))
            << Describe(row);
    }
}

TEST(ClockTests, AFractionOfASecondReadsAsTheSecondItIsInside)
{
    // The table is whole seconds; `epochSeconds` is a double and a frame lands wherever it lands.
    // A truncating conversion gets this wrong on the negative side only, which is exactly the case
    // a table of positive instants would never reach.
    for (const double offset : {0.0, 0.25, 0.5, 0.999})
    {
        EXPECT_EQ(CivilFromEpochSeconds(offset).second, 0) << offset;
        EXPECT_EQ(CivilFromEpochSeconds(-1.0 + offset).second, 59) << offset;
        EXPECT_EQ(CivilFromEpochSeconds(-1.0 + offset).year, 2030) << offset;
    }
    // ...and the boundary itself belongs to the second it starts.
    EXPECT_EQ(CivilFromEpochSeconds(-1.0).second, 59);
    EXPECT_EQ(CivilFromEpochSeconds(0.0).year, 2031);
}
